branch-defaults:
  master:
    environment: ProductionChartercommission-env
environment-defaults:
  ProductionChartercommission-env:
    branch: null
    repository: null
  QaChartercommission-env:
    branch: null
    repository: null
  QaChartercommission-env-1:
    branch: null
    repository: null
global:
  application_name: Production-CharterCommission
  branch: null
  default_ec2_keyname: jchei-nycc-aws
  default_platform: Ruby 2.3 (Puma)
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
